### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by KeitaW** [KeitaW/miscnotes#1]
- [ ]  Summarize Gardner Capacity
- [ ]   Proof of convergence of perception
- [ ]   Replica method on sk-model
